[package]
name = "logitray"
version = "1.0.2"
edition = "2024"
description = "Lightweight tray app to inspect/control Logitech G devices (DPI, lighting) over HID++ 2.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
anyhow = "1.0.104"
hidapi = { version = "2.6.7", default-features = false, features = ["windows-native"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.26.0"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Registry", "Win32_System_Console", "Win32_UI_Shell", "Win32_System_Threading", "Win32_System_SystemInformation", "Win32_Graphics_Gdi", "Win32_UI_HiDpi", "Win32_Globalization", "Win32_System_Diagnostics_ToolHelp"] }

[build-dependencies]
winresource = "0.1"
